[build]
    base="./"
    command="pnpm run build"
    publish="dist"

[functions]
    node_bundler = "esbuild"
    directory = "functions"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
